version: '3'
services:
  redis:
    image: redis
    command: redis-server
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    ports:
      - "5442:5432"
  celery:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: celery -A medfinder worker -l debug -E
    volumes:
      - .:/code
      - media:/media
    depends_on:
      - postgres
      - redis
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - media:/media
    depends_on:
      - postgres
      - redis
      - celery
volumes:
  media:
    driver: local
  redis:
