version: '3'
services:
  redis:
    image: redis
    command: redis-server
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    ports:
<<<<<<< HEAD
      - "5442:5432"
  celery:
=======
      - "5432:5432"
  django:
>>>>>>> e24130f6f08be34fdf93cbfe25fd7762b65526be
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - media:/media
    depends_on:
      - postgres
      - redis
      - celery
  celerybeat:
    image: medfinder-api_django
    command: celery -A medfinder beat -l info
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
  celery:
    image: medfinder-api_django
    command: celery -A medfinder worker -l debug -E
    volumes:
      - .:/code
      - media:/media
    depends_on:
      - postgres
      - redis
volumes:
  media:
    driver: local
  redis:
