version: '3'
services:
  redis:
    image: redis
    command: redis-server
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"
  postgres:
    image: mdillon/postgis:10
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - data:/var/lib/postgresql/data/
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - media:/media
    depends_on:
      - postgres
      - redis
      - celery
  celerybeat:
    image: medfinder-api_django
    command: celery -A medfinder beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    volumes:
      - .:/code
      - media:/media
    depends_on:
      - postgres
      - redis
  celery:
    image: medfinder-api_django
    command: celery -A medfinder worker -l debug -E -Q celery,signals
    volumes:
      - .:/code
      - media:/media
    depends_on:
      - postgres
      - redis
volumes:
  data:
    driver: local
  media:
    driver: local
  redis:
