version: '3'
services:
  redis:
    image: redis
    command: redis-server
    volumes:
      - redis:/data
  postgres:
    image: mdillon/postgis:10
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - static:/static:ro
      - media:/media:ro
    ports:
      -"80:80"
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: uwsgi --ini=./compose/django/uwsgi.ini
    volumes:
      - media:/media
    depends_on:
      - postgres
      - redis
      - celery
  celerybeat:
    image: medfinder-api_django
    command: celery -A medfinder beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    volumes:
      - media:/media
    depends_on:
      - postgres
      - redis
  celery:
    image: medfinder-api_django
    command: celery -A medfinder worker -E -Q celery,signals
    volumes:
      - media:/media
    depends_on:
      - postgres
      - redis
